-- Initialize MySQL database for ZENITH
-- Aligned with Drizzle schema.ts
CREATE DATABASE IF NOT EXISTS zenith CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE zenith;

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  unionId VARCHAR(255),
  username VARCHAR(50),
  password VARCHAR(255),
  name VARCHAR(255),
  email VARCHAR(320),
  avatar TEXT,
  role ENUM('user', 'admin') DEFAULT 'user' NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  lastSignInAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Banks table
CREATE TABLE IF NOT EXISTS banks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(50) NOT NULL DEFAULT '\u81ea\u5b9a\u4e49',
  color VARCHAR(20) NOT NULL DEFAULT '#00d4ff',
  cover VARCHAR(255),
  questionsJson LONGTEXT NOT NULL,
  chaptersJson LONGTEXT,
  progress INT NOT NULL DEFAULT 0,
  importedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  lastPracticedAt TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Practice records table
CREATE TABLE IF NOT EXISTS practice_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId BIGINT UNSIGNED NOT NULL,
  bankId BIGINT UNSIGNED NOT NULL,
  mockExamId BIGINT UNSIGNED,
  questionId INT NOT NULL,
  chapterId INT,
  chapterName VARCHAR(255),
  selected TEXT NOT NULL,
  isCorrect INT UNSIGNED NOT NULL,
  timeSpent INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Mock exams table
CREATE TABLE IF NOT EXISTS mock_exams (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  bankId BIGINT UNSIGNED NOT NULL,
  bankName VARCHAR(255),
  questionsJson LONGTEXT NOT NULL,
  questionCount INT NOT NULL DEFAULT 0,
  practicedCount INT NOT NULL DEFAULT 0,
  lastPracticedAt TIMESTAMP NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Daily records table
CREATE TABLE IF NOT EXISTS daily_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId BIGINT UNSIGNED NOT NULL,
  date VARCHAR(10) NOT NULL,
  count INT NOT NULL DEFAULT 0,
  correct INT NOT NULL DEFAULT 0,
  UNIQUE KEY unique_daily (userId, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- User settings table
CREATE TABLE IF NOT EXISTS user_settings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId BIGINT UNSIGNED NOT NULL UNIQUE,
  dailyGoal INT NOT NULL DEFAULT 20,
  reminderTime VARCHAR(10) NOT NULL DEFAULT '20:00',
  difficulty INT NOT NULL DEFAULT 3,
  fontSize VARCHAR(10) NOT NULL DEFAULT 'medium',
  questionLanguage VARCHAR(10) NOT NULL DEFAULT 'entc',
  theme VARCHAR(10) NOT NULL DEFAULT 'system'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
